name: General PR Review

on:
  pull_request:
    types: [opened, edited]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Get list of changed files
      id: changed-files
      run: |
        # Get list of changed files
        PR_NUMBER=${{ github.event.pull_request.number }}
        CHANGED_FILES=$(gh pr diff $PR_NUMBER | grep '^diff --git' | sed 's/^diff --git a\///' | awk '{print $1}')
        
        # Check if any of the changed files are in the /package directory
        echo "Changed files: $CHANGED_FILES"
        
        if echo "$CHANGED_FILES" | grep -q '^package/'; then
          echo "Changes detected in /package directory"
          echo "FILES_CHANGED=true" >> $GITHUB_ENV
        else
          echo "No changes in /package directory"
          echo "FILES_CHANGED=false" >> $GITHUB_ENV
        fi

    - name: Remove PR author from reviewers
      if: env.FILES_CHANGED == 'false'
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        PR_AUTHOR=$(gh pr view $PR_NUMBER --json author --jq '.author.login')
        if [ -n "$PR_AUTHOR" ]; then
          # Get current reviewers
          REVIEWERS=$(gh api /repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviewers --jq '.users[].login')
          for REVIEWER in $REVIEWERS; do
            if [ "$REVIEWER" = "$PR_AUTHOR" ]; then
              gh api --method DELETE /repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/requested_reviewers --field reviewers=$PR_AUTHOR
            fi
          done
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set PR approval requirements
      if: env.FILES_CHANGED == 'false'
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        gh api --method PATCH /repos/$GITHUB_REPOSITORY/branches/main/protection \
          -F required_approving_review_count=1
        # Request default reviewers
        gh api --method POST /repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/requested_reviewers \
          -f reviewers=barbosarebc,gitmantovani,LevitaSofia,JoaoPedro-Ribeiro,kaiquemota
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check and Enforce branch protection
      if: env.FILES_CHANGED == 'false'
      run: |
        gh api --method PATCH /repos/$GITHUB_REPOSITORY/branches/main/protection \
          -F required_approving_review_count=1 \
          -F required_reviewers=username1,username2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
