name: Merge Master

on:
  push:
    branches:
      - master

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Backend Validations and Deploy
      run: |
        #TO-DO DEPLOY
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      
    - name: Frontend Validations and Deploy
      uses: ./.github/workflows/frontend-deploy-prd