name: Merge Master

on:
  push:
    branches:
      - master

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
          ref: master

    - name: Backend Validations and Deploy
      run: |
        #TO-DO DEPLOY
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      
    - name: Frontend Validations and Deploy
      run:  |
        echo "VERCEL DEPLOY IN PRD STARTING"

        echo "Install Vercel CLI"
        npm install --global vercel

        echo "Pull Vercel Environment Information"
        vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

        echo "Build Project Artifacts"
        vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

        echo "Deploy to Production"
        vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}