name: Merge Master

on:
  push:
    branches:
      - master

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
          ref: master

    - name: Frontend Validations and Deploy
      run:  |
        echo "VERCEL DEPLOY IN PRD STARTING"

        echo -e "\nInstall Vercel CLI"
        npm install --global vercel

        echo -e "\nPull Vercel Environment Information"
        vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

        echo -e "\nBuild Project Artifacts"
        vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

        echo -e "\nDeploy to Production"
        vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}