name: Server PR Review

on:
  pull_request:
    types: [opened, edited]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Get list of changed files
      id: changed-files
      run: |
        # Get list of changed files
        PR_NUMBER=${{ github.event.pull_request.number }}
        CHANGED_FILES=$(gh pr diff $PR_NUMBER | grep '^diff --git' | sed 's/^diff --git a\///' | awk '{print $1}')
        
        # Check if any of the changed files are in the /package/server directory
        echo "Changed files: $CHANGED_FILES"
        
        if echo "$CHANGED_FILES" | grep -q '^package/server/'; then
          echo "Files changed in /package/server directory"
          echo "FILES_CHANGED=true" >> $GITHUB_ENV
        else
          echo "No changes in /package/server directory"
          echo "FILES_CHANGED=false" >> $GITHUB_ENV
        fi

    - name: Set PR approval requirements
      if: env.FILES_CHANGED == 'true'
      run: |
        # Remove all previous approvals
        PR_NUMBER=${{ github.event.pull_request.number }}
        gh pr review $PR_NUMBER --remove-review

        # Add default reviewers
        gh pr review $PR_NUMBER --request-reviewer barbosarebc,gitmantovani,LevitaSofia,JoaoPedro-Ribeiro,kaiquemota
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Remove PR author from reviewers
      if: env.FILES_CHANGED == 'false'
      run: |
        PR_AUTHOR=$(gh pr view ${{ github.event.pull_request.number }} --json author --jq '.author.login')
        if [ -n "$PR_AUTHOR" ]; then
          gh pr review ${{ github.event.pull_request.number }} --remove-reviewer $PR_AUTHOR
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check and Enforce branch protection
      if: env.FILES_CHANGED == 'true'
      run: |
        gh api --method PATCH /repos/$GITHUB_REPOSITORY/branches/main/protection \
          -F required_approving_review_count=1 
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
